name: Gated-Windows
on:
 push:
   branches:
    - master
    - dev
 pull_request:
   branches:
    - master
    - dev

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2.2.0
      id: filter
      with:
        filters: |
          src:
          - 'src/**'
          - 'test/**'
          - '*.cmd'
          - '*.ps1'
          - '*.props'
          - '*.targets'
          - '*.sh'
          - '*.sln'
    - name: Update SubModules
      run: git submodule update --init --recursive
      if: steps.filter.outputs.src == 'true'

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          3.1.x
          5.0.x

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore

